In [4]:
import os

DATA_PATH = "../data/PAMAP2"

print("Dataset path:", DATA_PATH)
print("\nContents:")

for item in os.listdir(DATA_PATH):
    print(item)

Dataset path: ../data/PAMAP2

Contents:
Optional
Protocol

In [5]:
protocol_path = os.path.join(DATA_PATH, "Protocol")

print("Protocol files:\n")

for item in os.listdir(protocol_path):
    print(item)

Protocol files:

subject101.dat
subject102.dat
subject103.dat
subject104.dat
subject105.dat
subject106.dat
subject107.dat
subject108.dat
subject109.dat

In [6]:
protocol_files = [
    f for f in os.listdir(protocol_path)
    if f.endswith(".dat")
]

print("Number of protocol files:", len(protocol_files))
print("\nFiles:")
print(protocol_files)

Number of protocol files: 9

Files:
['subject101.dat', 'subject102.dat', 'subject103.dat', 'subject104.dat', 'subject105.dat', 'subject106.dat', 'subject107.dat', 'subject108.dat', 'subject109.dat']

In [7]:
import pandas as pd

first_file = os.path.join(protocol_path, protocol_files[0])

df = pd.read_csv(
    first_file,
    sep=r"\s+",
    header=None
)

print("File:", protocol_files[0])
print("Shape:", df.shape)

File: subject101.dat
Shape: (376417, 54)

In [8]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,44,45,46,47,48,49,50,51,52,53
0,8.38,0,104.0,30.0,2.37223,8.60074,3.51048,2.43954,8.76165,3.35465,...,0.008300,0.009250,-0.017580,-61.1888,-38.9599,-58.1438,1.0,0.0,0.0,0.0
1,8.39,0,NaN,30.0,2.18837,8.56560,3.66179,2.39494,8.55081,3.64207,...,-0.006577,-0.004638,0.000368,-59.8479,-38.8919,-58.5253,1.0,0.0,0.0,0.0
2,8.40,0,NaN,30.0,2.37357,8.60107,3.54898,2.30514,8.53644,3.73280,...,0.003014,0.000148,0.022495,-60.7361,-39.4138,-58.3999,1.0,0.0,0.0,0.0
3,8.41,0,NaN,30.0,2.07473,8.52853,3.66021,2.33528,8.53622,3.73277,...,0.003175,-0.020301,0.011275,-60.4091,-38.7635,-58.3956,1.0,0.0,0.0,0.0
4,8.42,0,NaN,30.0,2.22936,8.83122,3.70000,2.23055,8.59741,3.76295,...,0.012698,-0.014303,-0.002823,-61.5199,-39.3879,-58.2694,1.0,0.0,0.0,0.0

In [9]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 376417
Number of columns: 54

In [10]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 376417
Number of columns: 54

In [11]:
print("Unique activity IDs:")
print(sorted(df[1].dropna().unique()))

Unique activity IDs:
[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(12), np.int64(13), np.int64(16), np.int64(17), np.int64(24)]

In [12]:
print(df[1].value_counts().sort_index())

1
0     126460
1      27187
2      23480
3      21717
4      22253
5      21265
6      23575
7      20265
12     15890
13     14899
16     22941
17     23573
24     12912
Name: count, dtype: int64

In [13]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,44,45,46,47,48,49,50,51,52,53
0,8.38,0,104.0,30.0,2.37223,8.60074,3.51048,2.43954,8.76165,3.35465,...,0.008300,0.009250,-0.017580,-61.1888,-38.9599,-58.1438,1.0,0.0,0.0,0.0
1,8.39,0,NaN,30.0,2.18837,8.56560,3.66179,2.39494,8.55081,3.64207,...,-0.006577,-0.004638,0.000368,-59.8479,-38.8919,-58.5253,1.0,0.0,0.0,0.0
2,8.40,0,NaN,30.0,2.37357,8.60107,3.54898,2.30514,8.53644,3.73280,...,0.003014,0.000148,0.022495,-60.7361,-39.4138,-58.3999,1.0,0.0,0.0,0.0
3,8.41,0,NaN,30.0,2.07473,8.52853,3.66021,2.33528,8.53622,3.73277,...,0.003175,-0.020301,0.011275,-60.4091,-38.7635,-58.3956,1.0,0.0,0.0,0.0
4,8.42,0,NaN,30.0,2.22936,8.83122,3.70000,2.23055,8.59741,3.76295,...,0.012698,-0.014303,-0.002823,-61.5199,-39.3879,-58.2694,1.0,0.0,0.0,0.0

In [14]:
for i in range(df.shape[1]):
    print(i, df.iloc[0, i])

0 8.38
1 0
2 104.0
3 30.0
4 2.37223
5 8.60074
6 3.51048
7 2.43954
8 8.76165
9 3.35465
10 -0.0922174
11 0.0568115
12 -0.0158445
13 14.6806
14 -69.2128
15 -5.58905
16 1.0
17 0.0
18 0.0
19 0.0
20 31.8125
21 0.23808
22 9.80003
23 -1.68896
24 0.265304
25 9.81549
26 -1.41344
27 -0.00506495
28 -0.00678097
29 -0.00566295
30 0.47196
31 -51.0499
32 43.2903
33 1.0
34 0.0
35 0.0
36 0.0
37 30.3125
38 9.65918
39 -1.65569
40 -0.0997967
41 9.64689
42 -1.55576
43 0.310404
44 0.00830026
45 0.00925038
46 -0.0175803
47 -61.1888
48 -38.9599
49 -58.1438
50 1.0
51 0.0
52 0.0
53 0.0

In [15]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,44,45,46,47,48,49,50,51,52,53
0,8.38,0,104.0,30.0,2.37223,8.60074,3.51048,2.43954,8.76165,3.35465,...,0.008300,0.009250,-0.017580,-61.1888,-38.9599,-58.1438,1.0,0.0,0.0,0.0
1,8.39,0,NaN,30.0,2.18837,8.56560,3.66179,2.39494,8.55081,3.64207,...,-0.006577,-0.004638,0.000368,-59.8479,-38.8919,-58.5253,1.0,0.0,0.0,0.0
2,8.40,0,NaN,30.0,2.37357,8.60107,3.54898,2.30514,8.53644,3.73280,...,0.003014,0.000148,0.022495,-60.7361,-39.4138,-58.3999,1.0,0.0,0.0,0.0
3,8.41,0,NaN,30.0,2.07473,8.52853,3.66021,2.33528,8.53622,3.73277,...,0.003175,-0.020301,0.011275,-60.4091,-38.7635,-58.3956,1.0,0.0,0.0,0.0
4,8.42,0,NaN,30.0,2.22936,8.83122,3.70000,2.23055,8.59741,3.76295,...,0.012698,-0.014303,-0.002823,-61.5199,-39.3879,-58.2694,1.0,0.0,0.0,0.0

In [16]:
print(df.dtypes)

0     float64
1       int64
2     float64
3     float64
4     float64
5     float64
6     float64
7     float64
8     float64
9     float64
10    float64
11    float64
12    float64
13    float64
14    float64
15    float64
16    float64
17    float64
18    float64
19    float64
20    float64
21    float64
22    float64
23    float64
24    float64
25    float64
26    float64
27    float64
28    float64
29    float64
30    float64
31    float64
32    float64
33    float64
34    float64
35    float64
36    float64
37    float64
38    float64
39    float64
40    float64
41    float64
42    float64
43    float64
44    float64
45    float64
46    float64
47    float64
48    float64
49    float64
50    float64
51    float64
52    float64
53    float64
dtype: object

In [17]:
missing_values = df.isna().sum()

print("Total missing values:", missing_values.sum())

print("\nColumns containing missing values:")
print(missing_values[missing_values > 0])

Total missing values: 397958

Columns containing missing values:
2     342028
3       1454
4       1454
5       1454
6       1454
7       1454
8       1454
9       1454
10      1454
11      1454
12      1454
13      1454
14      1454
15      1454
16      1454
17      1454
18      1454
19      1454
20       509
21       509
22       509
23       509
24       509
25       509
26       509
27       509
28       509
29       509
30       509
31       509
32       509
33       509
34       509
35       509
36       509
37      1327
38      1327
39      1327
40      1327
41      1327
42      1327
43      1327
44      1327
45      1327
46      1327
47      1327
48      1327
49      1327
50      1327
51      1327
52      1327
53      1327
dtype: int64

In [18]:
print("Heart-rate missing values:", df[2].isna().sum())
print("Total rows:", len(df))
print("Heart-rate missing percentage:",
      df[2].isna().mean() * 100)

Heart-rate missing values: 342028
Total rows: 376417
Heart-rate missing percentage: 90.86412143978619

In [19]:
activity_counts = df[1].value_counts().sort_index()

print("Target activity distribution:")
print(activity_counts[activity_counts.index != 0])

Target activity distribution:
1
1     27187
2     23480
3     21717
4     22253
5     21265
6     23575
7     20265
12    15890
13    14899
16    22941
17    23573
24    12912
Name: count, dtype: int64

In [20]:
print("Number of target activities:",
      len(activity_counts[activity_counts.index != 0]))

Number of target activities: 12

In [21]:
column_names = [
    "timestamp",
    "activity_id",
    "heart_rate",

    # Hand IMU
    "hand_temperature",
    "hand_acc_x",
    "hand_acc_y",
    "hand_acc_z",
    "hand_acc_x6",
    "hand_acc_y6",
    "hand_acc_z6",
    "hand_gyro_x",
    "hand_gyro_y",
    "hand_gyro_z",
    "hand_mag_x",
    "hand_mag_y",
    "hand_mag_z",
    "hand_orientation_1",
    "hand_orientation_2",
    "hand_orientation_3",
    "hand_orientation_4",

    # Chest IMU
    "chest_temperature",
    "chest_acc_x",
    "chest_acc_y",
    "chest_acc_z",
    "chest_acc_x6",
    "chest_acc_y6",
    "chest_acc_z6",
    "chest_gyro_x",
    "chest_gyro_y",
    "chest_gyro_z",
    "chest_mag_x",
    "chest_mag_y",
    "chest_mag_z",
    "chest_orientation_1",
    "chest_orientation_2",
    "chest_orientation_3",
    "chest_orientation_4",

    # Ankle IMU
    "ankle_temperature",
    "ankle_acc_x",
    "ankle_acc_y",
    "ankle_acc_z",
    "ankle_acc_x6",
    "ankle_acc_y6",
    "ankle_acc_z6",
    "ankle_gyro_x",
    "ankle_gyro_y",
    "ankle_gyro_z",
    "ankle_mag_x",
    "ankle_mag_y",
    "ankle_mag_z",
    "ankle_orientation_1",
    "ankle_orientation_2",
    "ankle_orientation_3",
    "ankle_orientation_4"
]

print("Number of names:", len(column_names))
print("Number of columns:", df.shape[1])

Number of names: 54
Number of columns: 54